# Generated by Django 5.1.6 on 2025-02-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cae',
            new_name='Car',
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name_plural': 'cars'},
        ),
    ]
