# Generated by Django 5.1.6 on 2025-02-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('S', 'Tarefa concluída'), ('N', 'Tarefa não concluida')], max_length=1)),
            ],
        ),
    ]
